# Form implementation generated from reading ui file 'qt_test_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UI_Main_Window(object):
    def setupUi(self, qt_test_window):
        qt_test_window.setObjectName("qt_test_window")
        qt_test_window.resize(1200, 900)
        self.gridLayout = QtWidgets.QGridLayout(qt_test_window)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(qt_test_window)
        self.progressBar1 = QtWidgets.QProgressBar(qt_test_window)

        self.plot_hrrp = GraphicsLayoutWidget(qt_test_window)
        self.plot_hrrp.setObjectName("plot_ppg")
        self.gridLayout.addWidget(self.plot_hrrp, 0, 0, 1, 1)


        self.label1 = QtWidgets.QLabel()
        self.label1.setText('1')
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label1.setObjectName("label")
        self.label1.setFont(QtGui.QFont("Monaco", 20))
        self.gridLayout.addWidget(self.label1, 0, 1, 1, 1)

        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)


        self.pushButton = QtWidgets.QPushButton(qt_test_window)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)


        self.retranslateUi(qt_test_window)
        QtCore.QMetaObject.connectSlotsByName(qt_test_window)

    def retranslateUi(self, qt_test_window):
        _translate = QtCore.QCoreApplication.translate
        qt_test_window.setWindowTitle(_translate("qt_test_window", "EasyR4 mmWave Radar Capture"))
        self.pushButton.setText(_translate("qt_test_window", "Capture"))
        # self.exitButton.setText(_translate("qt_test_window", "Laser On"))
from pyqtgraph import GraphicsLayoutWidget
